#
# ----------------------------------------
# datasource
# ----------------------------------------
#
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33106/test?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
    tomcat:
      initialSize: 10
      max-active: 20
      maxIdle: 20
      max-wait: 60000
      min-idle: 1
      test-while-idle: true
      test-on-borrow: true
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1
      remove-abandoned: true
      remove-abandoned-timeout: 600
# ----------------------------------------------------
# Mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.bruce121
  configuration:
    map-underscore-to-camel-case: true